### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: *****/R$raw;

### ISSUE THREAD

**Issue by luohaoxin** [adwiv/android-fat-aar#82]
when I use gradle setting like this:
gradle-wrapper: distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip
classpath 'com.android.tools.build:gradle:2.3.3'
I run application get a crash.
so I try to use gradle setting like this:
gradle-wrapper: distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip
classpath 'com.android.tools.build:gradle:2.2.3'
then the application works properly
sorry,my english is poor

**Comment by hubaoyu** [comment]
i have the same issues.

**Comment by liuxiaoyao** [comment]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/inveno/commonlib/R$layout;
I have the same issues,my android studio version is 3.0, classpath 'com.android.tools.build:gradle:2.3.3' ,gradle-wrapper: distributionUrl=https://services.gradle.org/distributions/gradle-3.3-all.zip, 
how to do to solve this issuues?

**Comment by mazouri** [comment]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/inveno/commonlib/R$layout; I have the same issues

**Comment by lavia0229** [comment]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/laba/test/lintwo/R$layout; I have the same issue

**Comment by tommy8421** [comment]
it seems that the task embedRClass cannot product jar of new generated R*.java to bundle directory.
task embedRClass(type: org.gradle.jvm.tasks.Jar, dependsOn: collectRClass) {
    doLast{
      println "EMBED R CLASS"
      destinationDir file("$bundle_release_dir/libs/")
      from base_r2x_dir
    }
}

**Comment by Whoisurdady** [comment]
@tommy8421 Do you know how to solve this problem now?

**Comment by tommy8421** [comment]
@Whoisurdady To get the fixed version script, please visit: https://github.com/tommy8421/fat-aar-fixed

**Comment by liveei** [comment]
@tommy8421 
God ! you save my life !   it works with gradle:2.3.0 !!!
